# Generated by Django 5.0.6 on 2024-06-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirm_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='confirm_password',
            field=models.CharField(default='default_password', max_length=64),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
