# Generated by Django 5.0.6 on 2024-06-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_confirm_email_usuario_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirm_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
