# Generated by Django 5.0.6 on 2024-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('categoria', models.CharField(choices=[('menu_principal', 'Menu Principal'), ('almoco', 'Almoço'), ('vegetariano', 'Vegetariano'), ('sobremesa', 'Sobremesa'), ('pizza', 'Pizza'), ('infantil', 'Infantil'), ('bebida_nao_alcoolica', 'Bebida Não Alcoólica'), ('bebida_alcoolica', 'Bebida Alcoólica'), ('vinho', 'Vinho')], max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
