# Generated by Django 5.0.6 on 2024-06-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmenu',
            options={'ordering': ['nome_produto'], 'verbose_name': 'Item Menu', 'verbose_name_plural': 'Itens do Menu'},
        ),
        migrations.RenameField(
            model_name='itemmenu',
            old_name='nome',
            new_name='nome_produto',
        ),
    ]
