# Generated by Django 5.0.6 on 2024-06-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmenu',
            options={'verbose_name': 'Item Menu'},
        ),
    ]
